title:             'Jonh Doe'
email:             'jonh@doe.com'
username:          'jonhdoe'
# change to avatar-1 or avatar-2
avatar_url:        '/images/avatar-2.jpeg'
description:       'Thoughts, Articles and The Modern Web'
sub_name:          'Developer at Company'

baseurl:           '/'
url:               'http://doe.com'

excerpt_separator: '<!--more-->'

# paginate
paginate: 5
paginate_path:      /page/:num

# exclude folders for ci
exclude:            [vendor]

# permalink
permalink:          :title/

sass:
    dir:            _sass
    style:          compressed

# Build settings
markdown:           kramdown
